name: 'First Interaction'

on:
  issues:
    types: [ opened ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            # Thank You For Opening Your First Issue With the IPDK Project

            Some notes to point you at some helpful information:

            * Please make sure to read our [contributing guidelines](https://github.com/ipdk-io/ipdk/blob/main/CONTRIBUTING.md).
            * Feel free to review the list of [IPDK maintainers](https://github.com/ipdk-io/ipdk/blob/main/MAINTAINERS.md) if you need specific help from a maintainer.

          pr-message: |
            # Thank You For Opening Your First Pull Request With the IPDK Project

            Some notes to point you at some helpful information:

            * Please make sure to read our [contributing guidelines](https://github.com/ipdk-io/ipdk/blob/main/CONTRIBUTING.md).
            * Feel free to review the list of [IPDK maintainers](https://github.com/ipdk-io/ipdk/blob/main/MAINTAINERS.md) if you need specific help from a maintainer.
            * You can find the yaml for our CI jobs [here](https://github.com/ipdk-io/ipdk/tree/main/.github/workflows).
